### PR TITLE
4.34.0

### PR DESCRIPTION
**Pull request by SIkebe**

### CODE REVIEW

**Comment by takezoe** [comment]
Ah, I removed TravisCI integration in gitbucket organization because most of CI in our organization has already been migrated to GitHub Actions. We need to migrate this repository to GitHub Actions, too.

**Comment by SIkebe** [comment]
I see. Should I migrate to GitHub Actions in this PR, too?

**Comment by takezoe** [comment]
Yes, if you can. 🙇

**Comment by SIkebe** [comment]
@takezoe Could you remove the outdated status check for travis?
https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks

**Comment by takezoe** [comment]
Removed.

**Comment by SIkebe** [comment]
Are there extra steps to enable GitHub Actions or am I missing something?

**Comment by takezoe** [comment]
Hmm... Could you try to push again? It may trigger a build.

**Comment by SIkebe** [comment]
@takezoe Both push and close/reopen didn't work. So I created new branch on gitbucket org directly.

#30 seems to be working, so could you review that first?

**Review by takezoe — APPROVED** [review]
Merged #30 and this also looks good, of course. Great thanks!

**Pull request merged**
